### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by tuler** [kevnk/gulp-sendgrid#1]
I'm trying to migrate our email template pipeline from Mandrill to SendGrid.
We use foundation.

We're getting the following error:

```
gulp-sendgrid: SendGridError: Response error
gulp-sendgrid: TypeError: Cannot read property 'filter' of undefined
```
Any help is appreciated.

**Comment by kevnk** [comment]
Hi @tuler - it looks like you're getting some response error from SendGrid, which would prevent you from uploading your templates... 

Have you tried these troubleshooting methods? https://github.com/kevnk/gulp-sendgrid#troubleshooting

Let me know if those don't work for you.

**Comment by tuler** [comment]
Yes I did. The api key seems to be correct (69 chars).
The permission I found is called "Template Engine" and not "Transactional Templates" as the docs say.

Is there anything in the emails that can be out of order?
The [Mandrill plugin I use](https://github.com/ThamosIO/gulp-template-mandrill) uses a json configuration for each template, and I see your plugin tries to infer the template name from the email itself. Maybe something is failing...

Is there any other troubleshooting I can make?

**Comment by kevnk** [comment]
I don't have any other troubleshooting other than cloning this repo, [npm link](https://docs.npmjs.com/cli/link)ing it and throwing in some console.logs to see if you can get more info on why SendGrid is failing — or maybe SendGrid shows errored out attempts on their side somewhere in the admin?

Sorry, I wish I could be more help.

**Comment by tuler** [comment]
I'm investigating.

The call to `getTemplates` is returning 403 (access forbidden)

I tried to enabled all permissions, but it didn't work.
I called `http https://api.sendgrid.com/v3/scopes` with the API key I'm using.
It returns the following permissions:

```
{
    "scopes": [
        "templates.create",
        "templates.read",
        "templates.update",
        "templates.delete",
        "templates.versions.create",
        "templates.versions.read",
        "templates.versions.update",
        "templates.versions.delete",
        "templates.versions.activate.create"
    ]
}
```

**Comment by tuler** [comment]
My bad, I wasn't passing the api key correctly.

**Comment by kevnk** [comment]
Oh good! :+1: I'm happy you were able to figure it out... I was coming up with blanks.
