### ISSUE TITLE
gulp-sendgrid: ReferenceError: templateName is not defined

### ISSUE THREAD

**Issue by tuler** [kevnk/gulp-sendgrid#2]
I added a log line to `SendGrid.prototype.run` and it prints:

`create/update template 'Password Reset Request' version 'password-reset-request'`

Are these values acceptable?

**Comment by kevnk** [comment]
Looking at [SendGrid docs on templates](https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/templates.html), they look fine. Looks like the variable `templateName` in the plugin must not be defined. 

Taking a quick look now.

**Comment by kevnk** [comment]
@tuler Try npm installing v0.0.3 - I just pushed what I hope will be the fix — let me know otherwise

**Comment by tuler** [comment]
The first time I run all my 21 templates get created, but only 1 version is created. The other 20 calls to createVersion fail.

The second time I run (and on) I get 1 createVersion error, all templates are ok, except 1.

**Comment by tuler** [comment]
For this one I get `Name already exists` in the createVersion call

**Comment by tuler** [comment]
For some reason a template version was created inside the wrong template, after I deleted it, it runs ok now.

**Comment by kevnk** [comment]
Sounds like the first run may have issues, but once it's sorted and cleaned, your future runs are working?
